dist: xenial
matrix:
  include:
    - language: generic
      name: "Setup Script"
      before_install:
        - sudo apt-get dist-upgrade
        - sudo apt install 'ros-*-librealsense'
        - sudo modprobe uvcvideo
      script:
        - ./setup-kinetic.sh

    - language: node_js
      name: "Node Scripts"
      node_js: "lts/*"
      cache:
        directories:
          - node_modules
      before_install:
        - mkdir -p ~/.arlobot/rosmaps ~/catkin_ws/src
        - touch ~/.arlobot/rosmaps/dummymap.pgm ~/.arlobot/rosmaps/dummymap.yaml
        - cp scripts/dotarlobot/personalDataForBehavior.json ~/.arlobot/
        - ln -s ${TRAVIS_BUILD_DIR} ~/catkin_ws/src/ArloBot
        - cd node

    - language: node_js
      name: "Node Code Coverage"
      install:
        - npm install -g istanbul codecov
      script:
        - npm ci
        - istanbul cover ./node_modules/jasmine/bin/jasmine.js
        - codecov

    - language: node_js
      name: "React Website"
      node_js: "lts/*"
      cache:
        directories:
          - node_modules
      script:
        - npm test
        - npm run build
      before_install:
        - cd website
