dist: xenial
matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd src

    - language: node_js
      node_js: "lts/*"
      before_install:
        - mkdir -p ~/.arlobot/rosmaps ~/catkin_ws/src
        - touch ~/.arlobot/rosmaps/dummymap.pgm ~/.arlobot/rosmaps/dummymap.yaml
        - cp scripts/dotarlobot/personalDataForBehavior.json ~/.arlobot/
        - ln -s ${TRAVIS_BUILD_DIR} ~/catkin_ws/src/ArloBot
        - cd node
